In [5]:
from sklearn import datasets
iris=datasets.load_iris()
print(type(iris))

<class 'sklearn.utils.Bunch'>


In [6]:
print(iris.keys())

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [7]:
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [8]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [9]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [10]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [11]:
print(iris.data.shape)

(150, 4)


In [12]:
print(type(iris.target))

<class 'numpy.ndarray'>


In [13]:
print(type(iris.target_names))

<class 'numpy.ndarray'>


In [20]:
import pandas as pd
iris=datasets.load_iris()
df=pd.DataFrame(iris.data,columns=iris.feature_names)
print(df.head(3))

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2


In [31]:
import numpy as np
import sklearn.datasets
examples=[]
examples.append('example text 1')
examples.append('example text 2')
examples.append('example text 3')
target=np.zeros((3,),dtype=np.int64)
target[0]=0
target[1]=4
target[2]=2
dataset=sklearn.datasets.base.Bunch(data=examples, target=target)
print(dataset)                                        

{'data': ['example text 1', 'example text 2', 'example text 3'], 'target': array([0, 4, 2], dtype=int64)}


In [63]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from sklearn import datasets
iris=datasets.load_iris()
knn=KNeighborsClassifier(n_neighbors=6)
f=knn.fit(iris['data'],iris['target'])
print(f)
print(iris['data'].shape)
print(iris['target'].shape)
x_new=np.array([[12,3.5,1.4,0.2],[4,41,50,52]], dtype=np.float)
prediction=knn.predict(x_new)
print(prediction)
print(x_new.shape)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=6, p=2,
                     weights='uniform')
(150, 4)
(150,)
[1 2]
(2, 4)


In [72]:
from sklearn.model_selection import train_test_split
from sklearn import datasets
iris=datasets.load_iris()
X_train, X_test, y_train, y_test=train_test_split(iris['data'],iris['target'],test_size=0.3,
                                                  random_state=21,stratify=iris['target'])
knn=KNeighborsClassifier(n_neighbors=8)
knn.fit(X_train, y_train)
y_pred=knn.predict(X_test)
print("Test set predictions:\n {}".format(y_pred))
print(knn.score(X_test, y_test))


Test set predictions:
 [2 1 2 2 1 0 1 0 0 1 0 2 0 2 2 0 0 0 1 0 2 2 2 0 1 1 1 0 0 1 2 2 0 0 1 2 2
 1 1 2 1 1 0 2 1]
0.9555555555555556


In [79]:
from sklearn.model_selection import GridSearchCV
from sklearn import datasets
import numpy as np
iris=datasets.load_iris()
knn=KNeighborsClassifier()
X=iris['data']
y=iris['target']
param_grid={'n_neighbors':np.arange(1,50)}
knn_cv=GridSearchCV(knn, param_grid,cv=5)
knn_cv.fit(X,y)
knn_cv.best_params_
knn_cv.best_score_

0.98

In [89]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
df=pd.read_csv(filepath_or_buffer="pima-indians-diabetes.text")
df.info()

FileNotFoundError: [Errno 2] File b'pima-indians-diabetes.text' does not exist: b'pima-indians-diabetes.text'